/*
# Storage Buckets and Policies

## Overview
Creates two Supabase Storage buckets:

1. **public-assets** (public) — stores plan images, testimonial photos, blog post images,
   team member photos, how-it-works step images. Anyone can read; only admins can upload/update/delete.

2. **paid-content** (private) — stores PDFs and videos for plans. These are NOT publicly accessible.
   Only admins can upload/manage files. Customers access them only via temporary signed URLs
   generated by the `get-paid-content` edge function after payment verification.

## Policies

### public-assets bucket
- SELECT (read): public — `TO anon, authenticated USING (true)`
- INSERT (upload): admin only — `WITH CHECK (is_admin())`
- UPDATE: admin only
- DELETE: admin only

### paid-content bucket
- SELECT: admin only (public users get signed URLs from the edge function, not direct access)
- INSERT: admin only
- UPDATE: admin only
- DELETE: admin only

## Important Notes
1. The `paid-content` bucket is private — no public read policy. Customers never get direct storage access.
2. Signed URLs are generated server-side by the edge function using the service role key, with a short
   expiry (e.g. 60 minutes). The URL is returned to the customer's browser and works temporarily.
3. Admins upload paid content (PDFs/videos) directly to the `paid-content` bucket via the admin UI
   using the authenticated Supabase client.
*/

-- ============================================================
-- Create buckets
-- ============================================================

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'public-assets',
  'public-assets',
  true,
  52428800,  -- 50MB
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml']
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'paid-content',
  'paid-content',
  false,
  524288000,  -- 500MB for videos
  ARRAY[
    'application/pdf',
    'video/mp4',
    'video/webm',
    'video/quicktime'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- ============================================================
-- public-assets policies
-- ============================================================

DROP POLICY IF EXISTS "public_assets_read" ON storage.objects;
CREATE POLICY "public_assets_read" ON storage.objects
  FOR SELECT TO anon, authenticated
  USING (bucket_id = 'public-assets');

DROP POLICY IF EXISTS "public_assets_insert_admin" ON storage.objects;
CREATE POLICY "public_assets_insert_admin" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'public-assets' AND is_admin());

DROP POLICY IF EXISTS "public_assets_update_admin" ON storage.objects;
CREATE POLICY "public_assets_update_admin" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'public-assets' AND is_admin())
  WITH CHECK (bucket_id = 'public-assets' AND is_admin());

DROP POLICY IF EXISTS "public_assets_delete_admin" ON storage.objects;
CREATE POLICY "public_assets_delete_admin" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'public-assets' AND is_admin());

-- ============================================================
-- paid-content policies (private — admin only)
-- ============================================================

DROP POLICY IF EXISTS "paid_content_read_admin" ON storage.objects;
CREATE POLICY "paid_content_read_admin" ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'paid-content' AND is_admin());

DROP POLICY IF EXISTS "paid_content_insert_admin" ON storage.objects;
CREATE POLICY "paid_content_insert_admin" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'paid-content' AND is_admin());

DROP POLICY IF EXISTS "paid_content_update_admin" ON storage.objects;
CREATE POLICY "paid_content_update_admin" ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'paid-content' AND is_admin())
  WITH CHECK (bucket_id = 'paid-content' AND is_admin());

DROP POLICY IF EXISTS "paid_content_delete_admin" ON storage.objects;
CREATE POLICY "paid_content_delete_admin" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'paid-content' AND is_admin());
